### ISSUE TITLE
yandex api update

### ISSUE THREAD

**Issue by egoroof** [danpla/ymdl#1]
Hello!

I found that you use an old yandex music API ('/api/v1.4/...'). Try to download 2 different tracks and listen to it. It will be the same files. You can found updated api version here: https://github.com/egoroof/yandex-music-fisher/blob/master/src/js/yandex_api.js.

And it's interesting to me where are you from? Yandex music is available from Russia, Ukraine, Belarus and Kazakhstan. Are you from another country?

**Comment by danpla** [comment]
Hello!

Thanks for the tip!
I'm from Ukraine.
